export const CATEGORY_LABELS = {
  FRUTAS_VERDURAS: "Frutas y verduras",
  LACTEOS: "Lácteos",
  CARNE: "Carne",
  PESCADO: "Pescado",
  BEBIDAS: "Bebidas",
  PANADERIA: "Panadería",
  DESAYUNOS: "Desayunos",
  CAFE_INFUSIONES: "Café e infusiones",
  PASTA_ARROZ_LEGUMBRES: "Pasta, arroz y legumbres",
  CONSERVAS: "Conservas",
  HUEVOS: "Huevos",
  ACEITES_SALSAS_CONDIMENTOS: "Aceites, salsas y condimentos",
  CHARCUTERIA: "Charcutería",
  DULCES: "Dulces",
  APERITIVOS: "Aperitivos",
  PLATOS_PREPARADOS: "Platos preparados",
  CONGELADOS: "Congelados",
  HIGIENE: "Higiene",
  BELLEZA: "Belleza",
  LIMPIEZA: "Limpieza",
  MASCOTAS: "Mascotas",
  BEBE: "Bebé",
  FARMACIA: "Farmacia",
  OTROS: "Otros",
};

export const CATEGORY_COLORS = {
  FRUTAS_VERDURAS: "#A3D977",
  LACTEOS: "#FAD390",
  CARNE: "#FC6C6C",
  PESCADO: "#60A3D9",
  BEBIDAS: "#A084E8",
  PANADERIA: "#F5B971",
  DESAYUNOS: "#FFD166",
  CAFE_INFUSIONES: "#B08968",
  PASTA_ARROZ_LEGUMBRES: "#E9C46A",
  CONSERVAS: "#A8DADC",
  HUEVOS: "#FFE8A3",
  ACEITES_SALSAS_CONDIMENTOS: "#F4A261",
  CHARCUTERIA: "#E76F51",
  DULCES: "#F87D99",
  APERITIVOS: "#F7B267",
  PLATOS_PREPARADOS: "#B8C0FF",
  CONGELADOS: "#92DCE5",
  HIGIENE: "#CED2D2",
  BELLEZA: "#F0A6CA",
  LIMPIEZA: "#5BC0BE",
  MASCOTAS: "#D6A2E8",
  BEBE: "#FFCAD4",
  FARMACIA: "#BDE0FE",
  OTROS: "#CCCCCC",
};
